<html>
    <head>
        <title><?=$this->title?></title>
        <?=
           $this->keywords .
           $this->meta .
           $this->css
        ?>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"><?=$this->pageTitle?></a>
                </div>

            </div>
        </div>
        <?php
            $this->getViewContent();
        ?>
    <?=$this->js?>
    </body>
</html>
