<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
        <h1>Jey Roik - Вы точно такого не видели!</h1>
        <div class="list-group">
            <a href="/docs/traits" class="list-group-item">
                <h4 class="list-group-item-heading">
                    <span class="glyphicon glyphicon-signal"></span>
                    Уникальный в своём роде механизм, основанный на трейтах
                </h4>
                <p class="list-group-item-text">Низкий порог вхождения</p>
                <p class="list-group-item-text">Логичная структура</p>
            </a>
            <a href="/docs/events" class="list-group-item">
                <h4 class="list-group-item-heading">
                    <span class="glyphicon glyphicon-bell"></span>
                    Ядро основано на событиях
                </h4>
                <p class="list-group-item-text">Элементарна для понимания</p>
                <p class="list-group-item-text">Никогда ещё биндиг события не был таким удобным</p>
            </a>
            <a href="/docs/roles" class="list-group-item">
                <h4 class="list-group-item-heading">
                    <span class="glyphicon glyphicon-eye-open"></span>
                    Преждевременное разделение ролей
                </h4>
                <p class="list-group-item-text">Разграничения на уровне ядра</p>
            </a>
            <a href="/docs/mvc" class="list-group-item">
                <h4 class="list-group-item-heading">
                    <span class="glyphicon glyphicon-th-list"></span>
                    MVA - Model View Action
                </h4>
                <p class="list-group-item-text">Контроллеры на уровне конфигов</p>
                <p class="list-group-item-text">Удобное использование действий там, где они нужны</p>
            </a>
            <a href="/docs/extend" class="list-group-item">
                <h4 class="list-group-item-heading">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                    Грандиозная расширяемость
                </h4>
                <p class="list-group-item-text">Добавляйте что, когда и где угодно</p>
                <p class="list-group-item-text">Можно подключить абсолютно всё</p>
            </a>
        </div>
        <p><a class="btn btn-primary btn-lg" role="button">Learn more &raquo;</a></p>
    </div>
</div>
